replicaCount: 1

image:
  repository: "851725552187.dkr.ecr.eu-north-1.amazonaws.com/eladviprojservice2"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

mongodbUrl: "mongodb://mongodb:27017/service2"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
